package com.example.orderprocessing.service;

import com.example.orderprocessing.dto.OrderRequest; import com.example.orderprocessing.entity.*; import com.example.orderprocessing.repository.*; import org.springframework.scheduling.annotation.Async; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*; import java.util.concurrent.*; import java.util.concurrent.atomic.AtomicLong;
@Service public class OrderService {
  private final OrderRepository orders; private final ProductRepository products; private final EventHub events; private final OrderProcessor processor; private final AtomicLong sequence=new AtomicLong(1000);
  public OrderService(OrderRepository orders,ProductRepository products,EventHub events,OrderProcessor processor){this.orders=orders;this.products=products;this.events=events;this.processor=processor;}
  public CustomerOrder create(OrderRequest request){Product product=products.findById(request.productId()).orElseThrow(()->new NoSuchElementException("Product not found")); CustomerOrder order=orders.save(new CustomerOrder("ORD-"+sequence.incrementAndGet(),request.customerName(),product,request.quantity())); events.publish(orderView(order)); processor.process(order.getId()); return order;}
  public CustomerOrder retry(Long id){CustomerOrder order=orders.findById(id).orElseThrow(); if(order.getStatus()!=OrderStatus.DEAD_LETTER && order.getStatus()!=OrderStatus.FAILED) throw new IllegalStateException("Only failed orders can be retried"); order.retry(); orders.save(order); processor.process(id); return order;}
  public List<CustomerOrder> all(){return orders.findTop100ByOrderByCreatedAtDesc();} public CustomerOrder get(Long id){return orders.findById(id).orElseThrow();}
  public Map<String,Object> summary(){Map<String,Object> result=new LinkedHashMap<>(); result.put("total",orders.count()); for(OrderStatus status:OrderStatus.values())result.put(status.name().toLowerCase(),orders.countByStatus(status)); return result;}
  public Object orderView(CustomerOrder o){return Map.of("id",o.getId(),"orderNumber",o.getOrderNumber(),"customerName",o.getCustomerName(),"product",o.getProduct().getName(),"quantity",o.getQuantity(),"status",o.getStatus(),"retryCount",o.getRetryCount(),"failureReason",o.getFailureReason()==null?"":o.getFailureReason(),"updatedAt",o.getUpdatedAt());}
  public Map<String,Object> simulate(OrderRequest request,int number){long started=System.nanoTime(); for(int i=0;i<number;i++)create(request); try{Thread.sleep(1000);}catch(InterruptedException ignored){Thread.currentThread().interrupt();} Map<String,Object> result=new LinkedHashMap<>(summary()); result.put("durationMs",(System.nanoTime()-started)/1_000_000); result.put("requested",number); return result;}
}
