package com.example.orderprocessing.service;

import com.example.orderprocessing.dto.OrderRequest; import com.example.orderprocessing.entity.*; import com.example.orderprocessing.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*; import java.util.concurrent.atomic.AtomicLong;
@Service public class OrderService {
  private final OrderRepository orders; private final ProductRepository products; private final EventHub events; private final OrderProcessor processor; private final AtomicLong sequence=new AtomicLong(1000);
  public OrderService(OrderRepository orders,ProductRepository products,EventHub events,OrderProcessor processor){this.orders=orders;this.products=products;this.events=events;this.processor=processor;}
  public CustomerOrder create(OrderRequest request){Product product=products.findById(request.productId()).orElseThrow(()->new NoSuchElementException("Product not found")); String orderNumber="ORD-"+System.currentTimeMillis()+"-"+sequence.incrementAndGet(); CustomerOrder order=orders.save(new CustomerOrder(orderNumber,request.customerName(),product,request.quantity())); events.publish(orderView(order)); processor.process(order.getId()); return order;}
  public CustomerOrder retry(Long id){CustomerOrder order=orders.findById(id).orElseThrow(); if(order.getStatus()!=OrderStatus.DEAD_LETTER && order.getStatus()!=OrderStatus.FAILED) throw new IllegalStateException("Only failed orders can be retried"); order.retry(); orders.save(order); processor.process(id); return order;}
  public List<CustomerOrder> all(){return orders.findTop100ByOrderByCreatedAtDesc();} public CustomerOrder get(Long id){return orders.findById(id).orElseThrow();}
  public List<CustomerOrder> search(String query, OrderStatus status){return all().stream().filter(o->(query==null||query.isBlank()||o.getOrderNumber().toLowerCase().contains(query.toLowerCase())||o.getCustomerName().toLowerCase().contains(query.toLowerCase()))&&(status==null||o.getStatus()==status)).toList();}
  @Transactional public CustomerOrder changeStatus(Long id,OrderStatus status){CustomerOrder order=get(id);switch(status){case CONFIRMED->order.confirm();case SHIPPED->order.ship();case DELIVERED->order.deliver();case CANCELLED->order.cancel();default->throw new IllegalStateException("Unsupported manual status transition");} CustomerOrder saved=orders.save(order);events.publish(orderView(saved));return saved;}
  public Map<String,Object> summary(){Map<String,Object> result=new LinkedHashMap<>(); result.put("total",orders.count()); for(OrderStatus status:OrderStatus.values())result.put(status.name().toLowerCase(),orders.countByStatus(status)); return result;}
  public Object orderView(CustomerOrder o){Map<String,Object> view=new LinkedHashMap<>(); view.put("id",o.getId());view.put("orderNumber",o.getOrderNumber());view.put("customerName",o.getCustomerName());view.put("product",o.getProduct().getName());view.put("productId",o.getProduct().getId());view.put("quantity",o.getQuantity());view.put("unitPrice",o.getProduct().getPrice());view.put("status",o.getStatus());view.put("retryCount",o.getRetryCount());view.put("failureReason",o.getFailureReason()==null?"":o.getFailureReason());view.put("createdAt",o.getCreatedAt());view.put("updatedAt",o.getUpdatedAt());return view;}
  public Map<String,Object> simulate(OrderRequest request,int number){long started=System.nanoTime(); for(int i=0;i<number;i++)create(request); try{Thread.sleep(1000);}catch(InterruptedException ignored){Thread.currentThread().interrupt();} Map<String,Object> result=new LinkedHashMap<>(summary()); result.put("durationMs",(System.nanoTime()-started)/1_000_000); result.put("requested",number); return result;}
}
