package com.example.orderprocessing.service;
import com.example.orderprocessing.dto.*; import com.example.orderprocessing.entity.*; import com.example.orderprocessing.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class ProductService { private final ProductRepository repo; private final InventoryMovementRepository movements; public ProductService(ProductRepository repo,InventoryMovementRepository movements){this.repo=repo;this.movements=movements;} public List<Product> all(){return repo.findAll();} public Product get(Long id){return repo.findById(id).orElseThrow();}
	@Transactional public Product create(ProductRequest r){Product p=new Product(r.sku(),r.name(),r.inventory(),r.price()); p.updateDetails(r.name(),r.sku(),r.description(),r.price(),r.cost(),r.category(),r.reorderLevel()); Product saved=repo.save(p); if(r.inventory()>0) movements.save(new InventoryMovement(saved,MovementType.STOCK_IN,r.inventory(),0,r.inventory(),"Opening inventory","PRODUCT-"+saved.getId(),"system")); return saved;}
	@Transactional public Product update(Long id,ProductRequest r){Product p=get(id);p.updateDetails(r.name(),r.sku(),r.description(),r.price(),r.cost(),r.category(),r.reorderLevel());return repo.save(p);}
	@Transactional public Product addStock(Long id,int quantity){if(quantity<1)throw new IllegalArgumentException("Quantity must be positive");Product p=get(id);int before=p.getAvailableInventory();p.addStock(quantity);Product saved=repo.save(p);movements.save(new InventoryMovement(saved,MovementType.STOCK_IN,quantity,before,saved.getAvailableInventory(),"Stock received","PRODUCT-"+id,"system"));return saved;}
	@Transactional public Product adjust(Long id,InventoryAdjustmentRequest request){if(request.quantity()==0)throw new IllegalArgumentException("Quantity must not be zero");Product p=get(id);int before=p.getAvailableInventory();int delta=request.type()==MovementType.STOCK_IN||request.type()==MovementType.RETURN?Math.abs(request.quantity()): -Math.abs(request.quantity()); if(request.type()==MovementType.ADJUSTMENT)delta=request.quantity(); if(delta>0)p.addStock(delta);else p.adjustAvailable(delta);Product saved=repo.save(p);movements.save(new InventoryMovement(saved,request.type(),delta,before,saved.getAvailableInventory(),request.reason(),request.reference(),request.performedBy()==null?"system":request.performedBy()));return saved;}
	@Transactional public void delete(Long id){Product p=get(id);p.deactivate();repo.save(p);} @Transactional(readOnly=true) public List<?> movements(Long productId){List<InventoryMovement> result=productId==null?movements.findTop100ByOrderByCreatedAtDesc():movements.findByProductIdOrderByCreatedAtDesc(productId);return result.stream().map(this::movementView).toList();}
	private Map<String,Object> movementView(InventoryMovement movement){Map<String,Object> view=new LinkedHashMap<>();view.put("id",movement.getId());view.put("productId",movement.getProduct().getId());view.put("productName",movement.getProduct().getName());view.put("type",movement.getType());view.put("quantity",movement.getQuantity());view.put("availableBefore",movement.getAvailableBefore());view.put("availableAfter",movement.getAvailableAfter());view.put("reason",movement.getReason());view.put("reference",movement.getReference());view.put("performedBy",movement.getPerformedBy());view.put("createdAt",movement.getCreatedAt());return view;}
}
